swagger: "2.0"
info:
  title: API получения рассчитанных цен
  version: "4.12.1"
  description: Метод получения верхних групп и подгрупп рассчитанных цен с применением коллектора фильтров

paths:
  /api/detailed/collector/find-all:
    post:
      summary: Получение рассчитанных цен
      description: Возвращает иерархическую структуру рассчитанных цен с фильтрацией, пагинацией и сортировкой.
      tags:
        - Calculated Prices
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Параметры запроса для получения рассчитанных цен.
          required: true
          schema:
            type: object
            properties:
              filters:
                type: array
                description: Список фильтров
                items:
                  $ref: '#/definitions/Filter'
              offset:
                type: integer
                format: int64
                description: Смещение для пагинации.
              paged:
                type: boolean
                description: Флаг включения пагинации.
              pageNumber:
                type: integer
                format: int32
                description: Номер страницы.
              pageSize:
                type: integer
                format: int32
                description: Размер страницы.
              "sort.sorted":
                type: boolean
                description: Флаг сортировки (sorted).
              "sort.unsorted":
                type: boolean
                description: Флаг отсутствия сортировки (unsorted).
              unpaged:
                type: boolean
                description: Флаг отключения пагинации.
      responses:
        '200':
          description: Успешный ответ со списком рассчитанных цен
          schema:
            type: object
            properties:
              content:
                type: array
                items:
                  $ref: '#/definitions/UpperGroupCalculatedPricesDTO'
              totalSize:
                type: integer
                format: int64
                description: Общий размер набора данных.
                example: 100
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

definitions:
  Filter:
    type: object
    properties:
      key:
        type: string
        description: Ключ фильтра.
      searchCondition:
        type: string
        description: Условие поиска.
        enum:
          - CONTAINS
          - EQUALS
          - GREATER_THAN_OR_EQ
          - LESS_THAN_OR_EQ
          - LIKE
          - NOT_CONTAINS
          - RANGE
      inFilter:
        type: array
        description: Фильтр IN.
        items:
          type: object
      rangeFilter:
        type: object
        description: Фильтр диапазона.
      valueFilter:
        type: object
        description: Фильтр значения.

  RangeDtoBigDecimal:
    type: object
    properties:
      min:
        type: number
        format: double
        description: Минимальное значение.
      max:
        type: number
        format: double
        description: Максимальное значение.

  RangeDtoInt:
    type: object
    properties:
      min:
        type: integer
        format: int32
        description: Минимальное значение.
      max:
        type: integer
        format: int32
        description: Максимальное значение.

  Timestamp:
    type: object
    properties:
      date:
        type: integer
        description: День месяца.
      day:
        type: integer
        description: День недели.
      hours:
        type: integer
        description: Часы.
      minutes:
        type: integer
        description: Минуты.
      month:
        type: integer
        description: Месяц.
      nanos:
        type: integer
        description: Наносекунды.
      seconds:
        type: integer
        description: Секунды.
      time:
        type: integer
        format: int64
        description: Время в миллисекундах с начала эпохи.
      timezoneOffset:
        type: integer
        description: Смещение часового пояса.
      year:
        type: integer
        description: Год.

  OtherCompetitorPricesDto:
    type: object
    properties:
      prices:
        type: string
        description: Цены других конкурентов.
      range:
        $ref: '#/definitions/RangeDtoInt'
        description: Диапазон цен.

  StmAnalogueDTO:
    type: object
    properties: {}
    description: DTO аналога STM.

  UpperGroupCalculatedPricesDTO:
    type: object
    properties:
      agreedBy:
        type: string
        description: Согласовано кем.
      basicBasketAttribute:
        type: string
        description: Базовый атрибут корзины.
      brand:
        type: string
        description: Бренд.
      categorySegment:
        type: string
        description: Сегмент категории.
      coAccept:
        type: boolean
        description: Согласовано CO.
      commercialMarginThousandsPerMonth:
        type: integer
        description: Коммерческая маржа тысяч в месяц.
      competitiveEnvironment:
        type: string
        description: Конкурентное окружение.
      competitiveEnvironmentCount:
        type: integer
        description: Количество конкурентного окружения.
      competitorName:
        type: string
        description: Название конкурента.
      competitorPrice:
        $ref: '#/definitions/RangeDtoBigDecimal'
        description: Цена конкурента.
      declineExplanation:
        type: string
        description: Объяснение отклонения.
      declineExplanationComment:
        type: string
        description: Комментарий к объяснению отклонения.
      deviationPriceFromOld:
        $ref: '#/definitions/RangeDtoInt'
        description: Отклонение цены от старой.
      deviationPriceFromSelfCost:
        $ref: '#/definitions/RangeDtoInt'
        description: Отклонение цены от себестоимости.
      deviationPriceNewFromCompetitor:
        $ref: '#/definitions/RangeDtoInt'
        description: Отклонение новой цены от конкурента.
      deviationRecommendPriceFromNew:
        $ref: '#/definitions/RangeDtoInt'
        description: Отклонение рекомендованной цены от новой.
      environmentCluster:
        type: string
        description: Кластер окружения.
      environmentClusterCount:
        type: integer
        description: Количество кластеров окружения.
      finCode:
        type: string
        description: Финансовый код.
      finalPrice:
        $ref: '#/definitions/RangeDtoBigDecimal'
        description: Финальная цена.
      finalPriceType:
        type: string
        description: Тип финальной цены.
      frontMargin:
        type: number
        format: double
        description: Фронтальная маржа.
      id:
        type: string
        description: Идентификатор.
      influenceOnPtFm:
        type: integer
        description: Влияние на PT FM.
      isAccessControl:
        type: boolean
        description: Флаг контроля доступа.
      isDeclineExplanationCommentDifferent:
        type: boolean
        description: Флаг отличия комментария к объяснению отклонения.
      isDeclineExplanationDifferent:
        type: boolean
        description: Флаг отличия объяснения отклонения.
      isEditableStm:
        type: boolean
        description: Флаг редактируемости STM.
      isIncludeChangedGroups:
        type: boolean
        description: Флаг включения измененных групп.
      isLowerLadderDifferent:
        type: boolean
        description: Флаг отличия нижней лестницы.
      isMacroDifferent:
        type: boolean
        description: Флаг отличия макрорегиона.
      isPriceReasonToChangeDifferent:
        type: boolean
        description: Флаг отличия причины изменения цены.
      isPromoPricing:
        type: boolean
        description: Флаг промо-цены.
      isSinglePriceForPriceCluster:
        type: boolean
        description: Флаг единой цены для ценового кластера.
      isStmAnalogs:
        type: boolean
        description: Флаг аналогов STM.
      isTop:
        type: boolean
        description: Флаг TOP.
      isUpperLadderDifferent:
        type: boolean
        description: Флаг отличия верхней лестницы.
      key:
        type: integer
        format: int64
        description: Ключ.
      kmAccept:
        type: boolean
        description: Согласовано KM.
      kmPrice:
        $ref: '#/definitions/RangeDtoBigDecimal'
        description: Цена KM.
      ladderBroken:
        type: boolean
        description: Флаг сломанной лестницы.
      lastModifiedBy:
        type: string
        description: Последний изменивший.
      lastModifiedByCo:
        type: string
        description: Последний изменивший CO.
      lastModifiedTimestamp:
        type: string
        format: date-time
        description: Временная метка последнего изменения.
      lowerLadder:
        type: string
        description: Нижняя лестница.
      lowerLevelGroups:
        type: array
        description: Группы нижнего уровня.
        items:
          type: object
      macroRegion:
        type: string
        description: Макрорегион.
      marginNegative:
        type: boolean
        description: Флаг отрицательной маржи.
      marketRiseCreatedTimestamp:
        type: string
        format: date
        description: Временная метка создания подъема рынка.
      marketRiseDeletedTimestamp:
        $ref: '#/definitions/Timestamp'
        description: Временная метка удаления подъема рынка.
      marketRisePrice:
        type: number
        format: double
        description: Цена подъема рынка.
      marketRiseReason:
        type: string
        description: Причина подъема рынка.
      marketRiseUpdatedTimestamp:
        $ref: '#/definitions/Timestamp'
        description: Временная метка обновления подъема рынка.
      marketRisingStatus:
        type: integer
        description: Статус подъема рынка.
      newFrontMargin:
        $ref: '#/definitions/RangeDtoInt'
        description: Новая фронтальная маржа.
      newPrice:
        type: number
        format: double
        description: Новая цена.
      oldFrontMargin:
        $ref: '#/definitions/RangeDtoInt'
        description: Старая фронтальная маржа.
      oldPrice:
        $ref: '#/definitions/RangeDtoBigDecimal'
        description: Старая цена.
      oldSegmentIsEDLP:
        type: boolean
        description: Старый сегмент - EDLP.
      otherCompetitorPrices:
        $ref: '#/definitions/OtherCompetitorPricesDto'
        description: Цены других конкурентов.
      pluBasket:
        type: string
        description: Корзина PLU.
      pluCode:
        type: integer
        description: Код PLU.
      pluCount:
        type: integer
        description: Количество PLU.
      pluName:
        type: string
        description: Название PLU.
      priceCluster:
        type: string
        description: Ценовой кластер.
      priceClusterCount:
        type: integer
        description: Количество ценовых кластеров.
      priceRange:
        $ref: '#/definitions/RangeDtoBigDecimal'
        description: Ценовой диапазон.
      priceRangePercent:
        type: integer
        description: Процент ценового диапазона.
      priceSegment:
        type: string
        description: Ценовой сегмент.
      productLine:
        type: string
        description: Линейка продукта.
      productTurnoverToItems:
        type: number
        format: double
        description: Товарооборот к товарам.
      productTurnoverToMonetary:
        type: number
        format: double
        description: Товарооборот к денежным средствам.
      recommendedPrice:
        $ref: '#/definitions/RangeDtoBigDecimal'
        description: Рекомендованная цена.
      selfCost:
        $ref: '#/definitions/RangeDtoBigDecimal'
        description: Себестоимость.
      sendToApprove:
        type: boolean
        description: Отправить на утверждение.
      shopCount:
        type: integer
        description: Количество магазинов.
      shortPriceReasonToChange:
        type: string
        description: Краткая причина изменения цены.
      shortPriceReasonToChangeDescription:
        type: string
        description: Краткое описание причины изменения цены.
      stmAnalogues:
        type: array
        description: Аналоги STM.
        items:
          $ref: '#/definitions/StmAnalogueDTO'
      stmType:
        type: integer
        description: Тип STM.
      territory:
        type: string
        description: Территория.
      territoryCount:
        type: integer
        description: Количество территорий.
      ui3:
        type: string
        description: UI 3.
      ui4:
        type: string
        description: UI 4.
      upperLadder:
        type: string
        description: Верхняя лестница.
      vendorName:
        type: string
        description: Имя поставщика.
      costSourceType:
        type: string
        description: Источник закупочной цены.
        enum:
          - "Прайслисты Торг"
          - "Продажи за 7 дней"
          - "Продажи за 60 дней"
          - "Ручная загрузка"
      viewFlagKm:
        type: boolean
        description: Флаг просмотра KM.
      violationStrategyCo:
        type: string
        description: Стратегия нарушения CO.
 