swagger: '2.0'

host: back-release.k8s.pricing-dev-3.salt.x5.ru

info:
  description: Pricing Api documentation
  title: ЦО ТС5
  version: 4.12.1

securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey

tags:
- description: Monitoring Controller
  name: Новый мониторинг

- description: Monitoring History Controller
  name: История нового мониторинга

basePath: /

paths:

  /api/new-monitoring/collector/find-all:
    post:
      consumes:
      - application/json
      operationId: findGroupedMonitoringUsingPOST
      parameters:
      - description: filters
        in: body
        name: filters
        required: true
        schema:
          items:
            $ref: '#/definitions/Filter'
          type: array
      - format: int64
        in: query
        name: offset
        required: false
        type: integer
      - in: query
        name: paged
        required: false
        type: boolean
      - format: int32
        in: query
        name: pageNumber
        required: false
        type: integer
      - format: int32
        in: query
        name: pageSize
        required: false
        type: integer
      - in: query
        name: sort.sorted
        required: false
        type: boolean
      - in: query
        name: sort.unsorted
        required: false
        type: boolean
      - in: query
        name: unpaged
        required: false
        type: boolean
      produces:
      - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Slice«MonitoringGroupDTO»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - JWT: []
      summary: Получение сгруппированных мониторингов с применением коллектора фильтров
      tags:
      - Новый мониторинг

  /api/new-monitoring/history/collector/find-all:
    post:
      consumes:
      - application/json
      operationId: findMonitoringHistoryUsingPOST
      parameters:
      - description: filters
        in: body
        name: filters
        required: true
        schema:
          items:
            $ref: '#/definitions/Filter'
          type: array
      - format: int64
        in: query
        name: offset
        required: false
        type: integer
      - in: query
        name: paged
        required: false
        type: boolean
      - format: int32
        in: query
        name: pageNumber
        required: false
        type: integer
      - format: int32
        in: query
        name: pageSize
        required: false
        type: integer
      - in: query
        name: sort.sorted
        required: false
        type: boolean
      - in: query
        name: sort.unsorted
        required: false
        type: boolean
      - in: query
        name: unpaged
        required: false
        type: boolean
      produces:
      - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Slice«MonitoringGroupDTO»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - JWT: []
      summary: Получение истории сгруппированных мониторингов с применением коллектора
        фильтров
      tags:
      - История нового мониторинга

definitions:

#Основные схемы 

  Filter:
    properties:
      inFilter:
        items:
          type: object
        type: array
      key:
        type: string
      rangeFilter:
        $ref: '#/definitions/RangeDto«object»'
      searchCondition:
        enum:
        - CONTAINS
        - EQUALS
        - GREATER_THAN_OR_EQ
        - LESS_THAN_OR_EQ
        - LIKE
        - NOT_CONTAINS
        - RANGE
        type: string
      valueFilter:
        type: object
    required:
    - key
    - searchCondition
    title: Filter
    type: object

  Slice«MonitoringGroupDTO»:
    properties:
      content:
        items:
          $ref: '#/definitions/MonitoringGroupDTO'
        type: array
      empty:
        type: boolean
      first:
        type: boolean
      last:
        type: boolean
      number:
        format: int32
        type: integer
      numberOfElements:
        format: int32
        type: integer
      pageable:
        $ref: '#/definitions/Pageable'
      size:
        format: int32
        type: integer
      sort:
        $ref: '#/definitions/Sort'
    title: Slice«MonitoringGroupDTO»
    type: object

#Вспомогательные  схемы 
  Sort:
    properties:
      empty:
        type: boolean
      sorted:
        type: boolean
      unsorted:
        type: boolean
    title: Sort
    type: object

  Pageable:
    properties:
      offset:
        format: int64
        type: integer
      pageNumber:
        format: int32
        type: integer
      pageSize:
        format: int32
        type: integer
      paged:
        type: boolean
      sort:
        $ref: '#/definitions/Sort'
      unpaged:
        type: boolean
    title: Pageable
    type: object

  MonitoringGroupDTO:
    properties:
      addressCompCount:
        format: int32
        type: integer
      algorithmCheckDate:
        format: date
        type: string
      analogueComp:
        type: string
      approvedPrice:
        format: int32
        type: integer
      barcodeComp:
        type: string
      brand:
        type: string
      brandComp:
        type: string
      competitorAddress:
        type: string
      competitorPriceToSelfPriceDifference:
        format: int32
        type: integer
      competitorTypeOnDate:
        type: string
      currentPrice:
        $ref: '#/definitions/RangeDto«bigdecimal»'
      currentPriceMedian:
        type: number
      dateMonitoring:
        format: date
        type: string
      finCode:
        type: string
      id:
        format: int64
        type: integer
      isLastActualPrice:
        type: boolean
      isRecursive:
        type: boolean
      isUploadedToHive:
        type: boolean
      kmCheckDate:
        $ref: '#/definitions/Timestamp'
      macroRegion:
        type: string
      monitoringDateCount:
        format: int32
        type: integer
      monitoringDateMax:
        format: date
        type: string
      monitoringDateMin:
        format: date
        type: string
      monitoringType:
        type: string
      monitorings:
        items:
          $ref: '#/definitions/MonitoringDTO'
        type: array
        uniqueItems: true
      nameComp:
        type: string
      nettoComp:
        type: number
      pluCode:
        type: string
      pluLine:
        type: string
      pluName:
        type: string
      pluSegmentation:
        type: string
      prediction:
        type: string
      predictionExplanation:
        type: string
      priceCluster:
        type: string
      priceComp:
        type: number
      priceCount:
        format: int32
        type: integer
      priceMedianPromo:
        type: number
      priceMedianRegular:
        type: number
      promoDivisionName:
        type: string
      promoType:
        type: string
      ratioCurrentPriceToCompPrice:
        type: number
      ratioCurrentPriceToMedianCompPrice:
        type: number
      recursionInfo:
        type: string
      rto:
        type: number
      selfPrice:
        type: number
      source:
        type: string
      status:
        format: int32
        type: integer
      territory:
        type: string
      ui2Name:
        type: string
      ui3Name:
        type: string
      ui4Name:
        type: string
      url:
        type: string
      vendorName:
        type: string
      viewed:
        format: int32
        type: integer
    title: MonitoringGroupDTO
    type: object


  RangeDto«bigdecimal»:
    properties:
      max:
        type: number
      min:
        type: number
    title: RangeDto«bigdecimal»
    type: object

  Timestamp:
    properties:
      date:
        format: int32
        type: integer
      day:
        format: int32
        type: integer
      hours:
        format: int32
        type: integer
      minutes:
        format: int32
        type: integer
      month:
        format: int32
        type: integer
      nanos:
        format: int32
        type: integer
      seconds:
        format: int32
        type: integer
      time:
        format: int64
        type: integer
      timezoneOffset:
        format: int32
        type: integer
      year:
        format: int32
        type: integer
    title: Timestamp
    type: object

  MonitoringDTO:
    title: MonitoringDTO
    type: object
    properties:
      algorithmCheckDate:
        format: date
        type: string
      analogueComp:
        type: string
      approvedPrice:
        format: int32
        type: integer
      barcodeComp:
        type: string
      brand:
        type: string
      brandComp:
        type: string
      competitorAddress:
        type: string
      competitorPriceToSelfPriceDifference:
        format: int32
        type: integer
      competitorTypeOnDate:
        type: string
      currentPrice:
        type: number
      dateMonitoring:
        format: date
        type: string
      finCode:
        type: string
      id:
        type: string
      isLastActualPrice:
        type: boolean
      isUploadedToHive:
        type: boolean
      kmCheckDate:
        $ref: '#/definitions/Timestamp'
      macroRegion:
        type: string
      monitoringGroupId:
        format: int64
        type: integer
      monitoringType:
        type: string
      nameComp:
        type: string
      nettoComp:
        type: number
      pluCode:
        type: string
      pluLine:
        type: string
      pluName:
        type: string
      pluSegmentation:
        type: string
      prediction:
        type: string
      predictionExplanation:
        type: string
      priceCluster:
        type: string
      priceComp:
        type: number
      priceMedianPromo:
        type: number
      priceMedianRegular:
        type: number
      promoDivisionName:
        type: string
      promoType:
        type: string
      ratioCurrentPriceToCompPrice:
        type: number
      ratioCurrentPriceToMedianCompPrice:
        type: number
      rto:
        type: number
      selfPrice:
        type: number
      source:
        type: string
      status:
        format: int32
        type: integer
      territory:
        type: string
      ui2Name:
        type: string
      ui3Name:
        type: string
      ui4Name:
        type: string
      url:
        type: string
      vendorName:
        type: string
      viewed:
        format: int32
        type: integer
        

  RangeDto«object»:
    properties:
      max:
        type: object
      min:
        type: object
    title: RangeDto«object»
    type: object